### ISSUE TITLE
--version无法打印版本号

### ISSUE THREAD

**Issue by Moraxyc** [nezhahq/agent#102]
### 运行环境

Darwin Kernel Version 24.1.0: root:xnu-11215.41.3~13/RELEASE_ARM64_T8132 arm64

### Agent 版本

1.0.0

### 描述问题

`--version`无法打印版本信息

### 复现步骤

运行`./nezha-agent --version`，显示为空

### 验证

- [X] 我确认这是一个 nezha-agent 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
编译链接参数那里包名忘改了，过会会修
