### ISSUE TITLE
Agent Version 1.0.0 client issue

### ISSUE THREAD

**Issue by garislangit** [nezhahq/agent#103]
The current latest version, 1.0.0, seems to have a small bug. Upon successful installation, the agent doesn't start running. The agent log shows the following message:

2024/11/29 13:31:21 打开配置文件失败：open /opt/nezha/agent/config.yml: no such file or directory

I had to modify the installation script and downgrade the client version to 0.20.5 for it to work properly.

Thanks!

**Comment by Origin1699** [comment]
+1

**Comment by uubulb** [comment]
Please create the configuration file first
