### ISSUE TITLE
国内IPV6的机器安装不了

### ISSUE THREAD

**Issue by hd520131478** [nezhahq/agent#108]
### 运行环境

Debian 11

### Agent 版本

1.02

### 描述问题

<details>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 
                                 Dload  Upload   Total   Spent    Left  Speed
                                 
100  4586  100  4586    0     0   5894      0 --:--:-- --:--:-- --:--:--  5887
Installing...
Download nezha-agent release failed, check your network connectivity
</details>

### 复现步骤

<details> 
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 
                                 Dload  Upload   Total   Spent    Left  Speed
                                 
100  4586  100  4586    0     0   5894      0 --:--:-- --:--:-- --:--:--  5887
Installing...
Download nezha-agent release failed, check your network connectivity
</details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha-agent 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
抱歉，根据您提供的信息没有看出这是 nezha-agent 的问题。
建议您检查网络连接
