### ISSUE TITLE
error reading server preface: http2: frame too large

### ISSUE THREAD

**Issue by MarxWaKa** [nezhahq/agent#110]
### 运行环境

x86_64 x86_64 x86_64 GNU/Linux

### Agent 版本

1.0.2

### 描述问题

<details>上报系统信息失败: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large"</details>

### 复现步骤

![image](https://github.com/user-attachments/assets/ff2e2ef8-629b-43f1-ac31-6d018cbc189a)

### 附加信息

<details>无</details>

### 验证

- [ ] 我确认这是一个 nezha-agent 的问题。
- [ ] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by wisdomskip** [comment]
我也是这个问题

**Comment by e4stjun** [comment]
我也遇到这个问题。我的环境是用的k8s的ingress绑了两个域名做的dashboard和grpc的分流，然后上了证书。

**Comment by MarxWaKa** [comment]
找到问题了：dashboard前面有nginx代理且启用了ssl，要在agent客户端的config.yaml中修改以下参数tls:true
