### ISSUE TITLE
关于agent需要定时重启的问题

### ISSUE THREAD

**Issue by HereNoAg300L** [nezhahq/agent#112]
### 运行环境

Linux debian-12 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64

### Agent 版本

1.0.2

### 描述问题

查看agent状态时的错误日志
worker exit to main: reportStateDaemon exit: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR

### 复现步骤

无

### 附加信息

有的时候会发现dashboard上有服务器掉线,但是其实还是正常运行的,只需要重启agent之后dashboard上就重新上线了,发现了好几次,但是只记录了这一次的错误代码,之后碰到会补充,谢谢开发人员

### 验证

- [X] 我确认这是一个 nezha-agent 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
[v1.0.4](https://github.com/nezhahq/agent/releases/tag/v1.0.4) 改善了 gRPC 保活机制，可以试一下。
