### ISSUE TITLE
后台删除机子会出现异常

### ISSUE THREAD

**Issue by longxingze0925** [nezhahq/agent#113]
### 运行环境

GNU/Linux 6.8.0-48-generic x86_64

### Agent 版本

1.0.4

### 描述问题

<details></details>
后台服务器列表删除已经添加的机子，将其删除，刷新网页又会恢复删除前的机子，等于没有删成功

### 复现步骤

<details></details>
服务器列表将添加好的机子删除，刷新网页又会回来

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha-agent 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
服务停了再删
