### ISSUE TITLE
PC端安装agent运行报错没法安装

### ISSUE THREAD

**Issue by moneytree520** [nezhahq/agent#115]
### 运行环境

Windows server 2019 X64

### Agent 版本

0.20.5

### 描述问题

<details>执行策略更改
执行策略可帮助你防止执行不信任的脚本。更改执行策略可能会产生安全风险，如 https:/go.microsoft.com/fwlink/?LinkID=135170
中的 about_Execution_Policies 帮助主题所述。是否要更改执行策略?
[Y] 是(Y)  [A] 全是(A)  [N] 否(N)  [L] 全否(L)  [S] 暂停(S)  [?] 帮助 (默认值为“N”): Y
Invoke-WebRequest : 404: Not Found
所在位置 行:1 字符: 228
+ ... emoteSigned;Invoke-WebRequest https://raw.githubusercontent.com/nezha ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebExce
    ption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
C:\install.ps1 : 无法将“C:\install.ps1”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括
路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ C:\install.ps1 nezha.XXXX.xyz:443 xxxxxxxxxxx --tls
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\install.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

运行命令后出现这个提示</details>

### 复现步骤

<details>运行PC端的代码出现的，没法安装</details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha-agent 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
v0 windows 手动装吧
