### ISSUE TITLE
[BUG]设备在线但没有获取到IP导致Agent无法自动更新

### ISSUE THREAD

**Issue by pengcheng820** [nezhahq/agent#120]
### Environment

CentOS 7.9/ Ubuntu 22.04

### Agent Version

1.0.6/1.1.0/1.1.1

### Describe the bug

客户端Agent在线，首次安装是1.0.5能正常获取IP，然后自动升级到1.0.6，获取不到IP了，然后发现即便设备在线，没有获取到IP，Agent不会自动更新

![image](https://github.com/user-attachments/assets/f495e4bf-92ca-43b1-8267-3fbc8290bf02)

### To Reproduce

<details></details>

### Additional Context

<details></details>

### Validation

- [X] I confirm this is a bug about nezha-agent.
- [X] I have searched Issues and confirm this bug has been reported before.

**Comment by uubulb** [comment]
新版修了，改为重连获取 IP。
