### ISSUE TITLE
扬州内网DNS

### ISSUE THREAD

**Issue by yifayun** [nezhahq/agent#126]
### 运行环境

ubuntu2204

### Agent 版本

1.1.1

### 描述问题

<details></details>
扬州是独立内网DNS，和其他机房不一样，安装agnet后无法与面板通信，偶尔能通信个一两秒然后就断开，v0版本通过修改hosts可以正常通信，v1版本修改也无效

### 复现步骤

<details></details>
安装agent发现无法通信，尝试修改/etc/hosts直接指向域名或IP:端口均无效

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha-agent 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
直接填ip都不行 那跟dns还有啥关系

**Comment by cwhitez** [comment]
解决了吗！
