### ISSUE TITLE
自动掉线，重启service服务无法恢复

### ISSUE THREAD

**Issue by ifyz** [nezhahq/agent#127]
### 运行环境

Debian 12 x86-64

### Agent 版本

1.1.2

### 描述问题

<details></details>
Agent无故离线
nezha-agent  service提示： `哪吒监控 Agent was skipped because of an unmet condition check`
其他Agent没有出现离线情况

### 复现步骤

<details></details>
复现步骤不明

### 附加信息

<details></details>
○ nezha-agent.service - 哪吒监控 Agent
     Loaded: loaded (/etc/systemd/system/nezha-agent.service; enabled; preset: enabled)
     Active: inactive (dead) (Result: exit-code) since Mon 2024-12-09 20:51:39 CST; 2h 22min ago
   Duration: 2d 8h 7.360s
  Condition: start condition failed at Mon 2024-12-09 23:13:28 CST; 25s ago
             └─ ConditionFileIsExecutable=/opt/nezha/agent/nezha-agent was not met
    Process: 356 ExecStart=/opt/nezha/agent/nezha-agent -c /opt/nezha/agent/config.yml (code=exited, status=1/FAILURE)
   Main PID: 356 (code=exited, status=1/FAILURE)
        CPU: 3min 3.221s

Dec 09 20:49:39 zzz systemd[1]: nezha-agent.service: Failed with result 'exit-code'.
Dec 09 20:49:39 zzz systemd[1]: nezha-agent.service: Consumed 3min 3.221s CPU time.
Dec 09 20:51:39 zzz systemd[1]: nezha-agent.service: Scheduled restart job, restart counter is at 1.
Dec 09 20:51:39 zzz systemd[1]: Stopped nezha-agent.service - 哪吒监控 Agent.
Dec 09 20:51:39 zzz systemd[1]: nezha-agent.service: Consumed 3min 3.221s CPU time.
Dec 09 20:51:39 zzz systemd[1]: nezha-agent.service - 哪吒监控 Agent was skipped because of an unmet condition check (ConditionFileIsExecutable=/opt/nezha/agent/nezha-agent).
Dec 09 23:13:28 zzz systemd[1]: nezha-agent.service - 哪吒监控 Agent was skipped because of an unmet condition check (ConditionFileIsExecutable=/opt/nezha/agent/nezha-agent).

### 验证

- [X] 我确认这是一个 nezha-agent 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
这个错误信息表明 ConditionFileIsExecutable 没有通过，意味着文件 /opt/nezha/agent/nezha-agent 不存在或者没有可执行权限。您可以检查以下几点以解决问题：

1. 确认路径 /opt/nezha/agent/nezha-agent 是否存在。
2. 确认文件是否有可执行权限。可以使用命令 chmod +x /opt/nezha/agent/nezha-agent 赋予可执行权限。
3. 确认软件是否安装。如果文件不存在，可能需要重新安装软件。

请检查这些方面，并根据需要进行调整。
