### ISSUE TITLE
在Armbian系统上使用出现错误

### ISSUE THREAD

**Issue by ssxzi** [nezhahq/agent#130]
### 运行环境

Linux armbian 5.15.107-ophub

### Agent 版本

1.1.2

### 描述问题

Agent在[Armbian](https://github.com/ophub/amlogic-s9xxx-armbian)系统启动后无法正常上线
![PixPin_2024-12-10_15-12-34](https://github.com/user-attachments/assets/80ece14e-4708-4fcf-ac42-826e9e51cd51)

### 复现步骤

使用一键命令在[Armbian](https://github.com/ophub/amlogic-s9xxx-armbian)系统安装agent

### 验证

- [X] 我确认这是一个 nezha-agent 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
这大概率是一个网络问题。

在 `Armbian OS 24.5.0 Noble with Linux 5.15.156-ophub` 上没有复现。

**Comment by ssxzi** [comment]
> 这大概率是一个网络问题。可以尝试使用自定义 DNS。
> 
> 在 `Armbian OS 24.5.0 Noble with Linux 5.15.156-ophub` 上没有复现。

好的，我现在使用IP而不是域名，成功链接上了

**Comment by ssxzi** [comment]
dns: ["114.114.114.114"]
自定义 DNS是这样写吗？在/opt/nezha/agent/config.yml @uubulb

**Comment by uubulb** [comment]
> dns: ["114.114.114.114"] 自定义 DNS是这样写吗？在/opt/nezha/agent/config.yml @uubulb

```yaml
["114.114.114.114:53"]
```

或者
```yaml
- 114.114.114.114:53
```
