### ISSUE TITLE
开启温度监控以后用机器一个显示另外一台不显示

### ISSUE THREAD

**Issue by dyit-dalanmao** [nezhahq/agent#132]
同配置 同系统 开启温度监控后 一台显示 另外一台不显示

**Comment by dyit-dalanmao** [comment]
![Screenshot_2024-12-15-12-25-41-432_alook.browser.jpg](https://github.com/user-attachments/assets/d1ae1556-c27f-4255-9486-7950d5b654b2)

![Screenshot_2024-12-15-12-27-01-397_alook.browser.jpg](https://github.com/user-attachments/assets/739efaed-f1a0-4e86-b740-68b60681962b)
![Screenshot_2024-12-15-12-28-32-021_alook.browser.jpg](https://github.com/user-attachments/assets/9a23efe1-a055-42e0-95d2-994f246dac10)



一样的系统 debian 版本什么都一样 这个有 另外两台不出温度之类的
同样的情况还

**Comment by uubulb** [comment]
光凭几张网页截图又看不出来
另外没按照模板填
