### ISSUE TITLE
网络上报错误仍然存在

### ISSUE THREAD

**Issue by DreamYuande** [nezhahq/agent#139]
### 运行环境

系统  Microsoft Windows 10 Enterprise 2016 LTSB   CPU  Intel(R) Atom(TM) CPU Z3735F @ 1.33GHz 4 Physical Core

### Agent 版本

1.1.4

### 描述问题

<details></details>

![QQ20241215-095318](https://github.com/user-attachments/assets/af59b4ac-02eb-410e-b5ca-1a8438f65908)  

![QQ20241215-095329](https://github.com/user-attachments/assets/f2c253e4-967e-43e6-ac82-756f8772898d)

![QQ20241215-100107](https://github.com/user-attachments/assets/30632855-e21a-4723-88d8-8a19fa2163dd)

### 复现步骤

<details></details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha-agent 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
看下api返回的数据

**Comment by DreamYuande** [comment]
{
  "id": 19,
  "name": "[家里云]主机棒",
  "display_index": 99,
  "host": {
    "platform": "Microsoft Windows 10 Enterprise 2016 LTSB",
    "cpu": [
      "Intel(R) Atom(TM) CPU  Z3735F @ 1.33GHz 4 Physical Core"
    ],
    "mem_total": 2087858176,
    "disk_total": 30672941056,
    "arch": "i686",
    "boot_time": 1730506564,
    "version": "1.1.4"
  },
  "state": {
    "cpu": 13.505747126436782,
    "mem_used": 1217921024,
    "disk_used": 22687567872,
    "net_in_transfer": 2925857586051809300,
    "net_out_transfer": 2308359718315229000,
    "net_in_speed": 1176821039104,
    "net_out_speed": 1705102016512,
    "uptime": 3752132,
    "load_1": 4.55771282e-315,
    "load_5": 4.07400204e-315,
    "load_15": 4.22194941e-315,
    "tcp_conn_count": 33,
    "udp_conn_count": 38,
    "process_count": 60
  },
  "country_code": "cn",
  "last_active": "2024-12-15T18:31:41.780957334+08:00"
}

**Comment by uubulb** [comment]
运行下这里的程序看下输出
https://go.dev/play/p/eE_gZqG5RWn

**Comment by DreamYuande** [comment]
![QQ20241215-184558](https://github.com/user-attachments/assets/5b42c3fe-99e1-4eea-a80e-d10be230cefc)
请问是这样吗

**Comment by uubulb** [comment]
在你的问题机器上运行

**Comment by DreamYuande** [comment]
网页是在问题机器上用谷歌浏览器打开的

**Comment by uubulb** [comment]
复制网页里的代码，编译后在你的机器上运行

**Comment by DreamYuande** [comment]
C:\Users\Administrator\Desktop\agent>main.exe
[{"name":"本地连接* 2","bytesSent":0,"bytesRecv":0,"packetsSent":0,"packetsRecv":0,"errin":0,"errout":0,"dropin":0,"dropout":0,"fifoin":0,"fifoout":0} {"name":"WLAN","bytesSent":2554835161149603840,"bytesRecv":3115413382090457088,"packetsSent":15024804918722560,"packetsRecv":12628805873041408,"errin":0,"errout":0,"dropin":0,"dropout":0,"fifoin":0,"fifoout":0} {"name":"蓝牙网络连接","bytesSent":0,"bytesRecv":0,"packetsSent":0,"packetsRecv":0,"errin":0,"errout":0,"dropin":0,"dropout":0,"fifoin":0,"fifoout":0} {"name":"Loopback Pseudo-Interface 1","bytesSent":0,"bytesRecv":0,"packetsSent":0,"packetsRecv":0,"errin":0,"errout":0,"dropin":0,"dropout":0,"fifoin":0,"fifoout":0}]

**Comment by uubulb** [comment]
wlan网卡数据是有点问题
目前可以确定至少不是 agent 的问题，可能是 gopsutil 的问题或者你自己设备的问题

**Comment by DreamYuande** [comment]
emm这个设备我买回来没动过网卡的设置

**Comment by uubulb** [comment]
可以去gopsutil开下issue

**Comment by DreamYuande** [comment]
有办法直接禁用掉网卡部分的监控吗
