### ISSUE TITLE
报警触发任务

### ISSUE THREAD

**Issue by heaid** [nezhahq/agent#2]
您好开发者，
在使用监控时，设置了这样一个报警
出站速度如果维持在8M-13M之间持续60秒（服务器正常出站速度会在30M/s-50M/s左右，有时候有qos就重启程序），就会报警通知
[{"type":"net_out_speed","min":13631488,"max":8388608,"duration":60,"cover":1,"ignore":{"14":true}}]
并执行一个重启程序的命令
我在观察了几次每次都有一段时间，就是说触发报警条件没有达到要求，有时候也会报警。并触发任务
而且如果设置了 始终触发，这个重启命令会一直触发，
按理说不应该是触发后，速度归零，在次达到报警条件才会再次触发任务吗？
正常是，我手动重启程序，服务器出站速度归零后，程序启动后速度会立刻回到30-50M/s
但是如果用哪吒监控，会一直维持在重启状态，不停地执行。
![image](https://github.com/nezhahq/agent/assets/57695239/0c68c287-99f1-4dd4-95ad-9ade1d133b25)

**Comment by naiba** [comment]
这是个滑动窗口，窗口期内超限需要有新数据进来冲淡窗口内的数据
