### ISSUE TITLE
Agent监控TrueNAS的硬盘出现错误

### ISSUE THREAD

**Issue by emoless789** [nezhahq/agent#95]
我使用TrueNAS手动部署了nezha agent，希望能够监控NAS的硬盘使用量
使用了./nezha-agent edit 来更改监控的硬盘
TrueNAS设置：
![屏幕截图 2024-11-24 165359](https://github.com/user-attachments/assets/8be33181-8639-49ea-a6ce-d07068a4e4d6)
一个存储池，里面有四个数据集
我希望能监控存储池的使用量，一开始我是这么选的：
![屏幕截图 2024-11-24 165203](https://github.com/user-attachments/assets/d868874c-1896-4d2b-8a9f-6d09c17483c2)
发现监控上只显示128k/1.51T
总量正确，但是已使用不对
![屏幕截图 2024-11-24 165611](https://github.com/user-attachments/assets/8d88b85f-dbfb-43cb-98df-790bb8737fef)
然后尝试选择所有数据集
![屏幕截图 2024-11-24 165659](https://github.com/user-attachments/assets/923162ad-4c3b-440c-9717-8aa237bb7e2a)
但是显示仍然错误
![屏幕截图 2024-11-24 165732](https://github.com/user-attachments/assets/71e0638e-b5ef-4c74-b3d6-ea1ba4bc4c3b)
已使用正确，但是总剩余量错误
最后尝试选择所有挂载数据的区域
![屏幕截图 2024-11-24 165829](https://github.com/user-attachments/assets/c47ff227-a50d-43cb-8a08-97518ff9391c)
仍然存在问题
![image](https://github.com/user-attachments/assets/2fd0b8a6-7a74-4399-8f67-4d55de87c75f)
希望能够得到解决

**Comment by uubulb** [comment]
是因为你用的zfs存储池的关系，每个挂载点的总量就是你的zfs存储池容量
